version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Pack
          command: zip -r resourcepack.zip ./*
      - run:
          name: Create pack folder
          command: mkdir packed/
      - run:
          name: Create pack folder
          command: mv resourcepack.zip packed/
      - store_artifacts:
          path: packed/
          destination: .
